[build]
  command = "npm run build"
  publish = "dist"
  functions = "src/functions"
  NODE_ENV = "10.15.3"

[dev]
  command = "npm run start"

# resolve the "new" URL to a function
[[redirects]]
  from = "/submitForm"
  to = "/.netlify/functions/submitForm"
  status = 200